application: emerald-oxide-88913
version: 1
runtime: go
api_version: go1

handlers:
- url: /app(.*)/
  static_files: app\1/index.html
  upload: app
  login: required
- url: /public
  static_dir: public
- url: /api(.*)
  login: required
  auth_fail_action: unauthorized
  script: _go_app
- url: /.*
  script: _go_app

skip_files:
  - bower_components
  - node_modules
  - stylesheets
  - app