application: testable
version: 1
runtime: go
api_version: go1

handlers:
- url: /app(.*)/
  static_files: app\1/index.html
  upload: app
  login: required
- url: /app(.*)
  static_files: app\1
  upload: app
  login: required
- url: /static
  static_dir: static
- url: /.*
  script: _go_app
