application: emerald-oxide-88913
version: 1
runtime: go
api_version: go1

handlers:
- url: /public
  static_dir: public
- url: /.*
  script: _go_app

skip_files:
  - bower_components
  - node_modules
  - stylesheets
  - app