application: testable
version: 1
runtime: go
api_version: go1

handlers:
- url: /api(.*)
  script: api
- url: /app(.*)/
  static_files: app\1/index.html
  upload: app
- url: /app(.*)
  static_files: app\1
  upload: app